# http server
port: ":8000"

# database
storage:
 username: "root"
 password: ""
 url: "test"

# static folder
staticFolder: "app/public"

# logging
systemLog:
 level: "debug"
 path: "boilerplate.log"
 logAppend: "true"
